# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  use_frameworks!
  pod 'AbstractTableView', :path => '../'

  # Pods for Example

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    # Pods for testing
  end

end
