language: objective-c
xcode_project: AbstractTableView.xcodeproj # path to your xcodeproj folder
xcode_scheme: AbstractTableViewTests
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)
