# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:

    macos:
      xcode: 12.5.1

    steps:
      - checkout
      - run: fastlane scan # Run tests using Fastlane
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output

  build-and-test:
    macos:
      xcode: 12.5.1
    steps:
      - run:
          name: Run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: WebTests